# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-16 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='address_english',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='employer',
            name='address_local',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='employer',
            name='business_license',
            field=models.ImageField(blank=True, upload_to=b'employer/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='name_local',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='employer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
