# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-17 14:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employers', '0003_auto_20170916_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='employer',
            old_name='address_english',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='employer',
            old_name='name_english',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='address_local',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='name_local',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='user',
        ),
        migrations.AddField(
            model_name='employercontact',
            name='employer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employers.Employer'),
        ),
        migrations.AddField(
            model_name='employercontact',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
