# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-17 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0004_auto_20170917_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employercontact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employercontact',
            name='name',
        ),
    ]
