# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-17 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0005_auto_20170917_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headers', models.TextField(blank=True, null=True)),
                ('document', models.FileField(upload_to=b'attachments/%Y/%m/%d/')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('employer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employers.Employer')),
            ],
        ),
    ]
