# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-18 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0007_auto_20170917_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerimages',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='employerrequirements',
            name='employer',
        ),
        migrations.AddField(
            model_name='employer',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employerdocument',
            name='document',
            field=models.FileField(upload_to=b'media/%Y/%m/%d/'),
        ),
        migrations.DeleteModel(
            name='EmployerImages',
        ),
        migrations.DeleteModel(
            name='EmployerRequirements',
        ),
    ]
