# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-18 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0009_auto_20170918_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='website',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='employer',
            name='zip',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
