# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-18 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0011_employerpricingschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerpricingschedule',
            name='region',
            field=models.IntegerField(choices=[(b'', b''), (1, b'1: Default'), (2, b'2: Mid-Hudson'), (3, b'3: NYC Metro')]),
        ),
        migrations.AlterField(
            model_name='employerpricingschedule',
            name='service_group',
            field=models.IntegerField(choices=[(b'', b''), (1, b'1: Standard Titles'), (2, b'2: Software/Hardware Specific Titles')]),
        ),
    ]
