# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-18 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0012_auto_20170918_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerpricingschedule',
            name='experience_level',
            field=models.CharField(blank=True, choices=[(b'', b''), (b'Junior', b'Junior (12-36 Months)'), (b'Mid Level', b'Mid Level (36-60 Months)'), (b'Senior', b'Senior (60-84 Months)'), (b'Expert', b'Expert (84+ Months)')], max_length=100),
        ),
        migrations.AlterField(
            model_name='employerpricingschedule',
            name='high_hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='employerpricingschedule',
            name='high_hourly_wage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
    ]
