# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-18 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0014_auto_20170918_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerpricingschedule',
            name='job_title',
            field=models.CharField(choices=[(b'', b''), (b'Business Analyst', b'Business Analyst'), (b'Project Manager', b'Project Manager'), (b'Tester', b'Tester'), (b'Programmer', b'Programmer'), (b'Technical Architect', b'Technical Architect'), (b'Technical Writer', b'Technical Writer'), (b'Specialist', b'Specialist'), (b'System Administrator', b'System Administrator'), (b'Database Administrator', b'Database Administrator'), (b'Technician V', b'Technician V'), (b'Principal Consultant', b'Principal Consultant'), (b'Technical Specialist 3', b'Technical Specialist 3'), (b'Technical Specialist 4', b'Technical Specialist 4'), (b'Technical Specialist 5', b'Technical Specialist 5'), (b'Software Architect #1', b'Software Architect #1'), (b'Software Architect #2', b'Software Architect #2'), (b'Architectural Specialist I', b'Architectural Specialist I'), (b'Architectural Specialist II', b'Architectural Specialist II'), (b'Sr. Production Control Operator', b'Sr. Production Control Operator'), (b'Production Control Operator', b'Production Control Operator'), (b'Sr. Equipment Operator', b'Sr. Equipment Operator'), (b'Equipment Operator', b'Equipment Operator'), (b'Service Delivery Specialist I', b'Service Delivery Specialist I'), (b'Service Delivery Specialist II', b'Service Delivery Specialist II')], max_length=200),
        ),
    ]
