# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-18 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0015_auto_20170918_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employerpricingschedule',
            old_name='normal_hourly_rate',
            new_name='hourly_rate',
        ),
        migrations.RenameField(
            model_name='employerpricingschedule',
            old_name='normal_hourly_wage',
            new_name='hourly_wage',
        ),
        migrations.RemoveField(
            model_name='employerpricingschedule',
            name='high_hourly_rate',
        ),
        migrations.RemoveField(
            model_name='employerpricingschedule',
            name='high_hourly_wage',
        ),
        migrations.AddField(
            model_name='employerpricingschedule',
            name='demand',
            field=models.CharField(blank=True, choices=[(b'', b''), (b'High', b'High'), (b'Normal', b'Normal')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='employerpricingschedule',
            name='experience_level',
            field=models.CharField(blank=True, choices=[(b'', b'Any'), (b'Junior', b'Junior (12-36 Months)'), (b'Mid Level', b'Mid Level (36-60 Months)'), (b'Senior', b'Senior (60-84 Months)'), (b'Expert', b'Expert (84+ Months)')], max_length=100, null=True),
        ),
    ]
