# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-18 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0016_auto_20170918_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerpricingschedule',
            name='demand',
            field=models.CharField(blank=True, choices=[(b'', b'Any'), (b'High', b'High'), (b'Normal', b'Normal')], max_length=25, null=True),
        ),
    ]
