# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-19 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0017_auto_20170918_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerpricingschedule',
            name='region',
            field=models.IntegerField(choices=[(b'', b''), (1, b'Default Region'), (2, b'Mid-Hudson Region'), (3, b'NYC Metro Region')]),
        ),
        migrations.AlterField(
            model_name='employerpricingschedule',
            name='service_group',
            field=models.IntegerField(choices=[(b'', b''), (1, b'Standard Titles'), (2, b'Software/Hardware Specific Titles')]),
        ),
    ]
