# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-17 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdocument',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.Job'),
        ),
    ]
