# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-18 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0008_auto_20170918_1128'),
        ('jobs', '0004_auto_20170917_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAdditionalInformationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=250, null=True)),
                ('value', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobQualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=250, null=True)),
                ('minimum_points', models.IntegerField()),
                ('maximum_points', models.IntegerField()),
                ('is_mandatory', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='JobRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=250, null=True)),
                ('value', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='jobrequirements',
            name='citizenship',
        ),
        migrations.RemoveField(
            model_name='jobrequirements',
            name='job',
        ),
        migrations.RemoveField(
            model_name='job',
            name='accommodation_included',
        ),
        migrations.RemoveField(
            model_name='job',
            name='accommodation_stipend',
        ),
        migrations.RemoveField(
            model_name='job',
            name='compensation_amount',
        ),
        migrations.RemoveField(
            model_name='job',
            name='compensation_terms',
        ),
        migrations.RemoveField(
            model_name='job',
            name='compensation_type',
        ),
        migrations.RemoveField(
            model_name='job',
            name='contract_completion_bonus',
        ),
        migrations.RemoveField(
            model_name='job',
            name='contract_length',
        ),
        migrations.RemoveField(
            model_name='job',
            name='contract_renew_bonus',
        ),
        migrations.RemoveField(
            model_name='job',
            name='insurance_included',
        ),
        migrations.RemoveField(
            model_name='job',
            name='insurance_stipend',
        ),
        migrations.RemoveField(
            model_name='job',
            name='location',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary_high',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary_low',
        ),
        migrations.RemoveField(
            model_name='job',
            name='travel_stipend',
        ),
        migrations.RemoveField(
            model_name='job',
            name='weekly_hours',
        ),
        migrations.AddField(
            model_name='job',
            name='employerContact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='employers.EmployerContact'),
        ),
        migrations.AlterField(
            model_name='jobdocument',
            name='document',
            field=models.FileField(upload_to=b'media/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='jobdocument',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='jobs.Job'),
        ),
        migrations.DeleteModel(
            name='JobRequirements',
        ),
        migrations.AddField(
            model_name='jobrequirement',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='jobs.Job'),
        ),
        migrations.AddField(
            model_name='jobqualification',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='jobs.Job'),
        ),
        migrations.AddField(
            model_name='jobadditionalinformationrequest',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additionalInformationRequests', to='jobs.Job'),
        ),
    ]
