# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-18 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0015_auto_20170918_1623'),
        ('jobs', '0005_auto_20170918_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobMandatoryQualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=250, null=True)),
                ('value', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobRequestedQualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=250, null=True)),
                ('minimum_points', models.IntegerField()),
                ('maximum_points', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='jobqualification',
            name='job',
        ),
        migrations.RemoveField(
            model_name='jobrequirement',
            name='job',
        ),
        migrations.AddField(
            model_name='job',
            name='agency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='max_submissions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='pricingSchedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='employers.EmployerPricingSchedule'),
        ),
        migrations.AddField(
            model_name='job',
            name='submission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='total_positions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='vendor_sumbmission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='JobQualification',
        ),
        migrations.DeleteModel(
            name='JobRequirement',
        ),
        migrations.AddField(
            model_name='jobrequestedqualification',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestedQualifications', to='jobs.Job'),
        ),
        migrations.AddField(
            model_name='jobmandatoryqualification',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandatoryQualifications', to='jobs.Job'),
        ),
    ]
