# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-18 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20170918_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='notes',
            new_name='description',
        ),
    ]
