# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-18 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20170918_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='employerContact',
            new_name='employer_contact',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='pricingSchedule',
            new_name='pricing_schedule',
        ),
    ]
