# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-19 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20170918_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequestedqualification',
            name='qualification_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
