# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-19 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_auto_20170919_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobadditionalinformationrequest',
            name='label',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobmandatoryqualification',
            name='label',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobrequestedqualification',
            name='label',
            field=models.TextField(blank=True, null=True),
        ),
    ]
