# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-19 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_auto_20170919_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='target_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
