# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-19 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_auto_20170919_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='vendor_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='jobdocument',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobdocument',
            name='file_type',
            field=models.CharField(blank=True, choices=[(b'', b'Other'), (b'Task Order Form', b'Task Order Form'), (b'Candidate Response Form', b'Candidate Response Form')], max_length=100, null=True),
        ),
    ]
