# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-19 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_auto_20170919_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='pricing_schedule',
        ),
        migrations.RemoveField(
            model_name='job',
            name='recruiter',
        ),
    ]
