# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-19 22:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_auto_20170919_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='vendor_sumbmission_date',
            new_name='vendor_submission_date',
        ),
    ]
