# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-20 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0019_auto_20170919_1401'),
        ('jobs', '0019_auto_20170919_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='pricing_schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='employers.EmployerPricingSchedule'),
        ),
    ]
