# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-19 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_job_pricing_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='preferred_hardware',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='preferred_software',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='work_hours',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
