# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-05 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_auto_20171019_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name=b'Published'),
        ),
    ]
