# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-15 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0022_auto_20180505_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
