# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-21 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('jobs', '0023_job_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='sites.Site'),
        ),
    ]
