# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-16 18:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0002_auto_20170916_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiter',
            name='image',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='thumb',
        ),
    ]
