# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-19 23:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0004_auto_20170919_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiter',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='location',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='phone_number',
        ),
    ]
