# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-17 14:42
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='citizenship',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
