# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-18 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170917_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[(b'Candidate', b'Candidate'), (b'Recruiter', b'Recruiter'), (b'Employer', b'Employer'), (b'Vendor', b'Vendor')], max_length=50),
        ),
    ]
