# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-16 18:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_year', models.CharField(max_length=4)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[(b'male', b'Male'), (b'female', b'Female')], max_length=10, null=True)),
                ('education', models.CharField(blank=True, choices=[(b'', b''), (b'High School', b'High School'), (b'Vocational School', b'Vocational School'), (b'Community College', b'Community College'), (b"Bachelor's Degree", b"Bachelor's Degree"), (b"Master's Degree", b"Master's Degree"), (b'MBA', b'MBA'), (b'PhD', b'PhD')], max_length=25)),
                ('education_major', models.CharField(blank=True, max_length=250)),
                ('current_location', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('image', models.ImageField(upload_to=b'employer/%Y/%m/%d')),
                ('thumb', models.ImageField(blank=True, upload_to=b'employer/%Y/%m/%d')),
                ('is_active', models.BooleanField(default=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to=b'candidate/%Y/%m/%d')),
                ('document_type', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=1)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_type', models.CharField(blank=True, choices=[(b'University', b'University'), (b'High School', b'High School'), (b'Middle School', b'Middle School'), (b'Primary School', b'Primary School'), (b'Kindergarten', b'Kindergarten'), (b'Youth Language Center', b'Youth Language Center'), (b'Adult Language Center', b'Adult Language Center')], max_length=25)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
