# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-16 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='image',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='thumb',
        ),
    ]
