# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-18 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_auto_20170916_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidaterequirements',
            name='user',
        ),
        migrations.RemoveField(
            model_name='candidatedocument',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='candidatedocument',
            name='is_active',
        ),
        migrations.AddField(
            model_name='candidatedocument',
            name='headers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidatedocument',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='candidates.Candidate'),
        ),
        migrations.AlterField(
            model_name='candidatedocument',
            name='document',
            field=models.FileField(upload_to=b'media/%Y/%m/%d/'),
        ),
        migrations.DeleteModel(
            name='CandidateRequirements',
        ),
    ]
