# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-10 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0022_auto_20180505_1302'),
        ('candidates', '0007_auto_20180510_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='email',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='candidate',
            name='first_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='candidate',
            name='last_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='candidate',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='candidateapplication',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='candidates.Candidate'),
        ),
        migrations.AddField(
            model_name='candidateapplication',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.Job'),
        ),
    ]
