# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-11 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0022_auto_20180505_1302'),
        ('candidates', '0009_auto_20180510_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateResponseMandatoryQualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responseText', models.TextField(blank=True, null=True)),
                ('candidateResponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandatoryQualifications', to='candidates.CandidateResponse')),
                ('mandatoryQualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidateResponses', to='jobs.JobMandatoryQualification')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateResponseRequestedQualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responseText', models.TextField(blank=True, null=True)),
                ('candidateResponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestedQualifications', to='candidates.CandidateResponse')),
                ('requestedQualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidateResponses', to='jobs.JobRequestedQualification')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='work_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidateresponse',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='candidates.Candidate'),
        ),
        migrations.AddField(
            model_name='candidateresponse',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='jobs.Job'),
        ),
    ]
