# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-11 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0010_auto_20180511_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='response_form_completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='response_form_sent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
