# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-11 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0012_auto_20180511_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='preferred_communication_method',
            field=models.CharField(blank=True, max_length=100, verbose_name=b'Communication'),
        ),
    ]
