# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-11 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0013_auto_20180511_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='initial_contact_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Contacted'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='response_form_completed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Form Completed'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='response_form_sent_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Form Sent'),
        ),
    ]
