# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-11 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0014_auto_20180511_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='referral_method',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
