# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-15 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0015_candidate_referral_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='skillset',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='status',
            field=models.CharField(blank=True, choices=[(b'New', b'New'), (b'Contacted', b'Contacted'), (b'Awaiting Response Form', b'Awaiting Response Form'), (b'Response Form Completed', b'Response Form Completed'), (b'Awaiting Interview', b'Awaiting Interview'), (b'Interview Completed', b'Interview Completed'), (b'Not Submitted', b'Not Submitted'), (b'Submitted', b'Submitted')], max_length=100, null=True),
        ),
    ]
