# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-21 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0016_auto_20180515_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(blank=True, choices=[(b'New', b'New'), (b'Contacted', b'Contacted'), (b'Awaiting Response Form', b'Awaiting Response Form'), (b'Response Form Completed', b'Response Form Completed'), (b'Awaiting Interview', b'Awaiting Interview'), (b'Interview Completed', b'Interview Completed'), (b'Additional Information Requested', b'Additional Information Requested'), (b'Not Submitted - Inexperienced', b'Not Submitted - Inexperienced'), (b'Not Submitted - Unqualified', b'Not Submitted - Unqualified'), (b'Not Submitted - Position Filled', b'Not Submitted - Position Filled'), (b'Submitted', b'Submitted')], max_length=100, null=True),
        ),
    ]
