# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-19 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_auto_20170919_1401'),
        ('jobs', '0016_auto_20170919_1444'),
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='jobs.Job')),
                ('message_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='campaigns.MessageTemplate')),
            ],
        ),
        migrations.CreateModel(
            name='MailCampaignVendorContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendorContacts', to='jobs.Job')),
                ('vendor_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='vendors.VendorContact')),
            ],
        ),
    ]
