# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-19 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_auto_20170919_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailcampaign',
            name='vendor_contacts',
            field=models.ManyToManyField(blank=True, to='vendors.VendorContact'),
        ),
    ]
