# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-19 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_auto_20170919_1401'),
        ('campaigns', '0005_auto_20170919_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailcampaign',
            name='candidates',
            field=models.ManyToManyField(blank=True, to='candidates.Candidate'),
        ),
    ]
