# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-12 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_mailcampaign_candidates'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailcampaign',
            name='email_sent_date',
            field=models.DateTimeField(null=True),
        ),
    ]
