# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-16 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_auto_20170916_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewinvitation',
            name='uuid',
            field=models.CharField(default=b'KDGHG', max_length=5, primary_key=True, serialize=False),
        ),
    ]
