# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-19 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0051_auto_20170920_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewinvitation',
            name='uuid',
            field=models.CharField(default=b'RF8BV', max_length=5, primary_key=True, serialize=False),
        ),
    ]
