# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-05 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0052_auto_20171019_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewinvitation',
            name='uuid',
            field=models.CharField(default=b'GY44U', max_length=5, primary_key=True, serialize=False),
        ),
    ]
