# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-05 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0053_auto_20180505_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewinvitation',
            name='uuid',
            field=models.CharField(default=b'MSJBJ', max_length=5, primary_key=True, serialize=False),
        ),
    ]
