# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-10 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0054_auto_20180505_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewinvitation',
            name='uuid',
            field=models.CharField(default=b'BWJQJ', max_length=5, primary_key=True, serialize=False),
        ),
    ]
