# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-10 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0055_auto_20180510_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewinvitation',
            name='uuid',
            field=models.CharField(default=b'2KAMS', max_length=5, primary_key=True, serialize=False),
        ),
    ]
