# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-21 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0068_auto_20180515_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewinvitation',
            name='uuid',
            field=models.CharField(default=b'ARPSH', max_length=5, primary_key=True, serialize=False),
        ),
    ]
